Output kustomize.nvim-deprecations.gif

Set WindowBar Colorful
Set Padding 5

Set FontSize 16
Set Width 1200
Set Height 700

Sleep 1s
Type@100ms "nvim ~/workspace/github.com/allaman/kustomize-demo/advanced/base/ingress.yaml"
Sleep 1s
Enter
Sleep 1s
Type@300ms ":KustomizeDeprecations"
Enter
Sleep 3s
Hide
Type ":NoiceDismiss"
Enter
Show
Type@300ms "ggjAbeta1"
Escape
Type ":w"
Enter
Sleep 5s
Type@300ms ":KustomizeDeprecations"
Enter
Sleep 5s
Hide
Type "u:wq"
Enter
Show
Sleep 2s
