Output kustomize.nvim-kinds.gif

Set WindowBar Colorful
Set Padding 5

Set FontSize 16
Set Width 1200
Set Height 700

Sleep 1s
Type@100ms "nvim ~/workspace/github.com/allaman/kustomize-demo/basic/overlay/dev/kustomization.yaml"
Sleep 1s
Enter
Sleep 1s
Type@300ms ":KustomizeBuild"
Enter
Sleep 2s
Type@300ms ":KustomizeListKinds"
Enter
Sleep 2s
Type@3s "jjjkkk"
Type "q"
Sleep 1s
Type "q"
Sleep 2s
Hide
Type ":q"
Enter
Show
Sleep 2s
