Output kustomize.nvim-build.gif

Set WindowBar Colorful
Set Padding 5

Set FontSize 16
Set Width 1200
Set Height 700

Sleep 1s
Type@100ms "nvim ~/workspace/github.com/allaman/kustomize-demo/basic/overlay/dev/kustomization.yaml"
Sleep 1s
Enter
Sleep 1s
Type@300ms ":KustomizeBuild"
Sleep 2s
Enter
Sleep 2s
Ctrl+d
Sleep 2s
Ctrl+d
Sleep 2s
Ctrl+d
Sleep 2s
Ctrl+d
Sleep 2s
Ctrl+d
Sleep 2s
Type "q"
Sleep 2s
Hide
Type ":q"
Enter
Sleep 2s
