Output kustomize.nvim-print.gif

Set WindowBar Colorful
Set Padding 5

Set FontSize 16
Set Width 1200
Set Height 700

Sleep 1s
Type@100ms "nvim ~/workspace/github.com/allaman/kustomize-demo/basic/base/bar/kustomization.yaml"
Sleep 1s
Enter
Sleep 1s
Type G
Sleep 0.5s
Type@500ms Vkkd
Sleep 1s
Type@300ms ":KustomizePrintResources"
Enter
Sleep 4s
Type@700ms jjjkk
Sleep 2s
Hide
Type ":q!"
Enter
Show
Sleep 2s
