Output kustomize.snippets.gif

Set WindowBar Colorful
Set Padding 5

Set FontSize 16
Set Width 1200
Set Height 700

Sleep 1s
Type@50ms "nvim ~/workspace/github.com/allaman/kustomize-demo/basic/overlay/dev/kustomization.yaml"
Sleep 1s
Enter
Sleep 1s
Type@300ms "G"
Sleep 1s
Type@300ms "o"
Sleep 1s
Backspace
Type@300ms "kust"
Sleep 3s
Tab
Sleep 3s
Tab
Sleep 3s
Tab
Sleep 3s
Hide
Escape
Escape
Type ":q!"
Enter
Sleep 3s

